import type {Metadata} from "next"; export const metadata:Metadata={title:"How EmberFire Research Works",description:"The research, evidence, correction, and publication standards of EmberFire Research."};
const principles=[
["Question before conclusion","Begin with a research question. Do not begin with a predetermined conclusion and collect only supporting material."],
["Primary sources first","When primary records, manuscripts, datasets, court records, archival documents, official publications, or original scholarship are available, use them. Secondary reporting provides context but does not replace accessible primary evidence."],
["Evidence states remain visible","Documented fact, scholarly interpretation, inference, allegation, tradition, hypothesis, and speculation are not interchangeable. Make the distinction visible to readers."],
["Serious disagreement is included","Where qualified specialists disagree, explain the competing interpretations and the evidence underlying them. Do not manufacture false balance where evidence is overwhelmingly one-sided."],
["Absence is not automatically proof","Failure to locate public evidence is not automatically evidence that something never existed. State what was searched, what is available, what is inaccessible, and what remains unknown."],
["Context is part of the evidence","Dates, provenance, textual transmission, institutional history, source relationships, and chronology can materially change the meaning of a claim. Do not strip them away for convenience."],
["Extraordinary claims require appropriate evidence","Interesting claims are not rejected merely because they are unusual. They also are not promoted beyond what the evidence supports."],
["Corrections remain visible","Material corrections receive a date and explanation. Do not silently rewrite the public record."],
["Versions matter",<>Published investigations have a publication date, current version, and last-reviewed or update date where applicable.</>],
["AI is a tool, not a source","AI systems may assist with organization, comparison, discovery, coding, transcription, or workflow. An AI output is not itself evidence for a factual claim. Claims still require inspectable sources."]
];
export default function Standards(){return <article className="prose-page"><span className="eyebrow">Editorial practice</span><h1>How EmberFire Research Works</h1><p className="statement">Research is only useful when a reader can tell where a claim came from, what evidence supports it, what remains uncertain, and what would change the conclusion.</p>{principles.map(([h,b],i)=><section className="principle" key={String(h)} id={i===7?"corrections":undefined}><h2>{i+1}. {h}</h2><p>{b}</p></section>)}<h2>Evidence states</h2><p>Where an investigation uses evidence labels, they mean:</p><dl><dt><strong>Documented</strong></dt><dd>Directly supported by accessible primary documentation or strong direct evidence.</dd><dt><strong>Supported</strong></dt><dd>Supported by multiple credible sources or converging evidence.</dd><dt><strong>Disputed</strong></dt><dd>Credible disagreement exists over interpretation.</dd><dt><strong>Unverified</strong></dt><dd>A claim exists but independent verification is insufficient.</dd><dt><strong>Unknown</strong></dt><dd>Available evidence cannot presently answer the question.</dd></dl><h2>Publication sequence</h2><ol>{["Define the question.","Build the source map.","Establish chronology.","Separate primary evidence from commentary.","Test the leading explanations.","Seek counterevidence and unresolved gaps.","Draft with source apparatus.","Review claims against evidence.","Assign publication metadata and version.","Publish the investigation and preserve later corrections."].map(x=><li key={x}>{x}</li>)}</ol></article>}
